# Generated by Django 4.2.28 on 2026-03-07 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layerindex', '0049_alter_layerbranch_vcs_subdir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='inherits',
            field=models.CharField(blank=True, max_length=383),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='license',
            field=models.CharField(blank=True, max_length=3072),
        ),
    ]
